steps:
 # build the container 
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '--network=cloudbuild','-t', 'gcr.io/firanse001/firansefood-web', '.']
   env: 
     - 'MAP_API_KEY=AIzaSyAkRCYqN9HQnj0Z5OIzCQ3E4sirgP246aw'
 # push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/firanse001/firansefood-web']
 # Deploy container image to Cloud Run
 - name: 'gcr.io/cloud-builders/gcloud'
   args: ['run', 'deploy', 'firanse-tech-firansefood-web', '--image', 'gcr.io/firanse001/firansefood-web', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']
images: 
- 'gcr.io/firanse001/firansefood-web'